# Generated by Django 5.1 on 2024-08-13 14:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(db_index=True, max_length=255)),
                ('track_name', models.CharField(max_length=255)),
                ('track_uri', models.CharField(max_length=255)),
                ('album_name', models.CharField(max_length=255)),
                ('album_art', models.URLField()),
                ('album_release_date', models.DateField()),
                ('artist_id', models.CharField(db_index=True, max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('artist_uri', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.recommendation')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.track')),
            ],
        ),
    ]
