# Generated by Django 5.1 on 2024-08-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='tracks',
            field=models.ManyToManyField(to='musicapp.track'),
        ),
        migrations.DeleteModel(
            name='RecommendationItem',
        ),
    ]
